ofxtools/Client.py
acctkeys should be a 1-tuple, not a string.
=> bugfix for creditcard accounts in Client.py

ofxtools/__init__.py
Seems like ofxtools is not compatible with python 3 actually?
AFAIK The relative implicit import in __init__ doesn't work:
from Client import OFXClient
from Parser import OFXTree
In Python 3.4:
File "D:\Documents\nYNABapi\pynYNAB\scripts\ofximport.py", line 3, in <module>
import ofxtools.Parser
File "C:\Python34\lib\site-packages\ofxtools\__init__.py", line 1, in <module>
from Client import OFXClient
ImportError: No module named 'Client'
=> fix relative import for py3 compatibility

ofxtools/Parser.py
I came across a bug in ofxtools when a OFX file is uploaded via apache because the python cgi module open the uploaded file in Bytes mode. When passing the file object to the parser, bytes are read instead of a string. This PR fixes this by decoding the bytes if the decode() function is available.
=> Add support for byte-like opened files

ofxtools/models/common.py, ofxtools/models/profile.py, ofxtools/models/signon.py
Only the first proprietary tag would remove from elementree because remove method reset the elementtree iterator.  This returns the iterator as a set list object instead.
This also removes proprietary tags from SONRS as well - support Merrill Edge qfx file downloads.
=> Fix multiple proprietary tags

ofxtools/Client.py
It really should've been request_accounts.
=> Fix typo in method name

ofxtools/Types.py, ofxtools/utils.py, tests/test_bank.py, tests/test_investment.py, tests/test_models_common.py, tests/test_profile.py, tests/test_seclist.py, tests/test_signon.py, tests/test_types.py
This pretty much makes sure that what goes up is UTC and what comes out is UTC.  It doesn't tell you what timezone the server responded in.
If you pass in naive times it assumes you mean local time.
Fixes #6
=> Support datetimes with timezones.  Return datetimes with timezones.

ofxtools/Client.py
Otherwise you get the following error:
```
File "/usr/local/bin/ofxget", line 11, in <module>
sys.exit(main())
File "/Users/fergbrain/Library/Python/2.7/lib/python/site-packages/ofxtools-0.5.1-py2.7.egg/ofxtools/Client.py", line 504, in main
do_profile(args)
File "/Users/fergbrain/Library/Python/2.7/lib/python/site-packages/ofxtools-0.5.1-py2.7.egg/ofxtools/Client.py", line 374, in do_profile
close_elements=not args.unclosedelements)
File "/Users/fergbrain/Library/Python/2.7/lib/python/site-packages/ofxtools-0.5.1-py2.7.egg/ofxtools/Client.py", line 159, in request_profile
dtprofup = datetime.datetime(1990, 1, 1, tz=UTC)
TypeError: 'tz' is an invalid keyword argument for this function
```
Compiled and works correctly now.
=> tz should be tzinfo

ofxtools/Types.py
I was following the Parser tutorials in the docs: https://ofxtools.readthedocs.io/en/latest/parser.html
```ofx = parser.convert()``` was failing with at line 395 in _convert_str with the following error
```ValueError: 20190213120000[0:GMT] does not conform to OFX formats for datetime```
Found the problem with the timestamp as shown below
I was pulling cc data from Chase and my transactions DatePosted Timestamps were missing the _millisecond group_ that appears before the timezone tag
```
<DTPOSTED>20190213120000[0:GMT]</DTPOSTED>
```
All other Timestamp Tags included the **millisecond group** as show below
```
<DTSTART>20181227152201.530[-5:EST]</DTSTART>
<DTEND>20190426152201.530[-4:EDT]</DTEND>
<DTSERVER>20190426152201.255[-4:EDT]</DTSERVER>
<DTASOF>20190426080000.000[-4:EDT]</DTASOF> …
```
=> Changed Datetime REGEX OFX Spec

ofxtools/Types.py
https://api.travis-ci.org/v3/job/685719134/log.txt
```
black --check .
would reformat /home/travis/build/csingley/ofxtools/ofxtools/Types.py
Oh no! ðŸ’¥ ðŸ’” ðŸ’¥
1 file would be reformatted, 94 files would be left unchanged.
Makefile:2: recipe for target 'test' failed
make: *** [test] Error 1
travis_time:end:04401dbf:start=1589211617811461855,finish=1589211628504921190,duration=10693459335,event=script
[0K[31;1mThe command "make test" exited with 2.[0m
Done. Your build exited with 1.
```
=> Fixing build failing due to black

ofxtools/models/invest/stmt.py
Some FIs use an employername longer than 32 characters
Addresses: https://github.com/csingley/ofxtools/issues/96
=> Use NagString for INV401K.employername

ofxtools/scripts/ofxget.py, tests/test_ofxget.py
This allows you to set `NEWFILEUID="NONE"` in the header for FIs which
don't like it being an actual UID.
Closes https://github.com/csingley/ofxtools/issues/98
=> ofxget: Add --nonewfileuid option

ofxtools/Client.py, ofxtools/scripts/ofxget.py, tests/test_ofxget.py
I've come across an FI which dislikes the HTTP User-Agent header being empty (coincidentally the same that doesn't like NEWFILEUID), but others have found FIs which dislike it containing different values... so is it time to parameterize it? This PR leaves the default behavior unchanged, but adds a parameter to `OFXClient` and a matching argument to `ofxget` to support overriding the user agent
This commit allows me to successfully make requests to this FI with ofxtools.
Question: Given our previous discussion about how to organize the arguments in `ofxget` - where would you like this one? I'm not sure I would think of an HTTP header as a 'formatting' argument, but I think it likely applies to the same set of subcommands...
=> Make User-Agent header configurable

ofxtools/Client.py
Some OFX gateways use a distinct URL for retrieving profiles,
this allows the user to specify that.
=> Allow distinct URL for request_profile()

ofxtools/Client.py
Some OFX gateways require non-standard http requests, e.g. preserving
cookies across requests or other custom headers. Instead of trying to
encode every possible custom transport sideband requirement, allow
user to provide custom URL opener to suit their specific use case,
while we only handle the standard OFX requirements.
This has the added benefit of allowing the user to use non-http
transports to retrieve OFX data, as well as potentially easing
testing.
=> Add cookie handling to OFXClient

ofxtools/scripts/ofxget.py
Support for password input via command line (or generic password input) #110
=> add --password to help with scripting.

ofxtools/Types.py, tests/test_types.py
Python's `divmod` function rounds towards negative infinity, so timezones with a
fractional negative offset would be off by one.
Add a test using Newfoundland Standard Time which demonstrates this problem.
=> Handle negative fractional timezone offsets.

ofxtools/scripts/ofxget.py
This is backward compatible with existing behavior: --clientuid, if used
bare without an id, will still generate and use a random id.
=> Allow --clientuid to accept an optional uuid. #127.

ofxtools/header.py, ofxtools/scripts/ofxget.py, tests/test_header.py, tests/test_ofxget.py
One of my banks returns OFXHeader V100 and VERSION 203 content. 
When ofxget scans with V200 headers, the server returns html error message content which fails OFX header parsing as expected. However the OFXHeaderError exceptions were not caught by ofxget - read_scan_response and the command terminates.
This was preventing me from scanning and getting acct info. Updated ofxget to catch the OFXHeaderErrors.
Secondly, OFXHeaderV1 was updated to relax verification of version. My understanding of the OFX standard is that V1XX can support V2XX messages.
=> Catch ofxget scan exceptions, allow V1 headers to support later versions

docs/installation.rst
Fix doc, once we are in ofxtools directory, we just need to refer to the file requirements-development.txt (and not ofxtools/requirements-development.txt)
=> https://github.com/csingley/ofxtools/issues/70

ofxtools/header.py
As the title says, I'm getting OFX V1 files with no COMPRESSION header (from University of Wisconsin Credit Union - UWCU) so made that group optional.
=> one of my banks does not send a COMPRESSION in V1 header
